language: python
services: sqlite
env:
    - DJANGO='django>=1.4,<1.5'
    - DJANGO='django>=1.5,<1.6'
    - DJANGO='django>=1.6,<1.7'
    - DJANGO='https://github.com/django/django/archive/stable/1.7.x.zip#egg=django'
python:
    - 3.4
    - 3.3
    - 2.7
    - 2.6
install:
    - pip install $DJANGO
    - python setup.py install
    - pip install -r requirements.txt
script: py.test tests/
matrix:
    exclude:
        - python: 3.3
          env: DJANGO='django>=1.4,<1.5'
        - python: 3.4
          env: DJANGO='django>=1.4,<1.5'
        - python: 2.6
          env: DJANGO='https://github.com/django/django/archive/stable/1.7.x.zip#egg=django'
